### ISSUE TITLE
Outdated data, wrong data for ILS

### ISSUE THREAD

**Issue by laukstein** [MicroPyramid/ratesapi#13]
When I try https://ratesapi.io/api/latest?base=GBP&symbols=ILS , it results:

![grabilla g11440](https://user-images.githubusercontent.com/183966/50730531-15ad8b80-1158-11e9-92f8-3cc3acdd16a2.png)

Issues:
1. API returns date 2019-01-04 while in Israel is now 2019-01-06. It seems more than a timezone issue, otherwise wouldn't return 2 days difference.
2. API returns too big difference for ILS, while Google would result 4.73, ratesapi returns 4.7028. There might be issue in it where expected maybe 4.728 instead of 4.7028.

**Comment by ashwin31** [comment]
@laukstein we are serving data gathered from european centrsl bank and 4th is friday where there may be no updates from banks till monday.

We are working on adding more sources for live data and better quality of data.

let us know if you know any reliable and re-distributable sources to get data from.
