### ISSUE TITLE
Question about API key and HTTPS encryption

### ISSUE THREAD

**Issue by DragonOsman** [MicroPyramid/ratesapi#15]
The info in the README doesn't mention anything about an API key.  Is it okay to take that to mean that this API doesn't require a key?  And is HTTPS encryption available on free subscriptions or do we have to upgrade to a paid account for that?

Any replies and help are appreciated.

**Comment by nikhila05** [comment]
@DragonOsman It's absolutely **free to use**. You can create any no of requests without any API key & no need of subscriptions for HTTPS encryption also.
